In [1]:

import pandas as pd
import numpy as np


In [30]:
## Reading a test matrix:
M = np.array([[5,2,4,4,3],[3,1,2,4,1],[2,np.nan,3,1,4],[2,5,4,3,5],[4,4,5,4,np.nan]])
print M
t= M[:,3].copy()
t[3] = 0
print t
print M[:,4]

[[  5.   2.   4.   4.   3.]
 [  3.   1.   2.   4.   1.]
 [  2.  nan   3.   1.   4.]
 [  2.   5.   4.   3.   5.]
 [  4.   4.   5.   4.  nan]]
[ 4.  4.  1.  0.  4.]
[  3.   1.   4.   5.  nan]


In [31]:
U = np.ones((5,2),dtype=np.float)
V = np.ones((2,5),dtype=np.float)
print "U:\n{}".format(U)
print "V:\n{}".format(V)
#U[:,1:]

U:
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
V:
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [54]:
#np.linalg.pinv(np.dot(V,V.T))
def array_sq(l):
    return np.dot(l,l.T)
np.apply_along_axis(array_sq,1,V)
np.nanmean(np.square(M - np.dot(U,V)))

3.2608695652173911

In [114]:
## Building U:
def build_U(M,U,V,r,s):
    #Get the s row from V
    V_s=V[s,:].copy()
    #Get the r row from M
    M_r=M[r,:].copy()
    
    #Get the r row from U
    U_r = U[r,:].copy()
    U_r[s] = 0
    #Get the r col from V
    V_r = V[:,r].copy()
    V_r[s] = 0
    print "V_s:{}".format(V_s)
    print "M_r:{}".format(M_r)
    print "U_r:{}".format(U_r)
    print "V_r:{}".format(V_r)
    M_r = M_r - np.dot(U_r,V_r)
    V_s[np.isnan(M_r)] = 0
    M_r[np.isnan(M_r)] = 0
    
    print "M_r:{}".format(M_r)
    return np.dot(V_s,M_r)/np.dot(V_s,V_s) 
r=0
s=0
U[r,s] = build_U(M,U,V,r,s)
print M    
print U

V_s:[ 1.  1.  1.  1.  1.]
M_r:[ 5.  2.  4.  4.  3.]
U_r:[ 0.  1.]
V_r:[ 0.  1.]
M_r:[ 4.  1.  3.  3.  2.]
[[  5.   2.   4.   4.   3.]
 [  3.   1.   2.   4.   1.]
 [  2.  nan   3.   1.   4.]
 [  2.   5.   4.   3.   5.]
 [  4.   4.   5.   4.  nan]]
[[ 2.6  1. ]
 [ 1.   1. ]
 [ 1.   1. ]
 [ 1.   1. ]
 [ 1.   1. ]]


In [115]:
## Building V:
def build_V(M,U,V,r,s):
    #Get the r col from U
    U_r=U[:,r].copy()
    #Get the s col from M
    M_s=M[:,s].copy()
        
    #Get the s col from V
    V_s = V[:,s].copy()
    V_s[r] = 0
    #Get the s row from U
    U_s = U[r,:].copy()
    U_s[r] = 0
    print "V_s:{}".format(V_s)
    print "M_s:{}".format(M_s)
    print "U_r:{}".format(U_r)
    print "U_s:{}".format(U_s)
    M_s = M_s - np.dot(V_s,U_s)
    U_r[np.isnan(M_s)] = 0
    M_s[np.isnan(M_s)] = 0
    
    print "M_s:{}".format(M_s)
    return np.dot(U_r,M_s)/np.dot(U_r,U_r) 
r=0
s=0
V[r,s] = build_V(M,U,V,r,s)
print M    
print V

V_s:[ 0.  1.]
M_s:[ 5.  3.  2.  2.  4.]
U_r:[ 2.6  1.   1.   1.   1. ]
U_s:[ 0.  1.]
M_s:[ 4.  2.  1.  1.  3.]
[[  5.   2.   4.   4.   3.]
 [  3.   1.   2.   4.   1.]
 [  2.  nan   3.   1.   4.]
 [  2.   5.   4.   3.   5.]
 [  4.   4.   5.   4.  nan]]
[[ 1.61710037  1.          1.          1.          1.        ]
 [ 1.          1.          1.          1.          1.        ]]


In [119]:
r=2
s=0
U[r,s]=build_U(M,U,V,r,s)
#print M    
#print V

V_s:[ 1.61710037  1.          1.          1.          1.        ]
M_r:[  2.  nan   3.   1.   4.]
U_r:[ 0.  1.]
V_r:[ 0.  1.]
M_r:[ 1.  0.  2.  0.  3.]


In [120]:
V

array([[ 1.61710037,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ]])

In [121]:
U

array([[ 2.6      ,  1.       ],
       [ 1.       ,  1.       ],
       [ 1.1784656,  1.       ],
       [ 1.       ,  1.       ],
       [ 1.       ,  1.       ]])

In [122]:
np.matmul(U,V)

array([[ 5.20446097,  3.6       ,  3.6       ,  3.6       ,  3.6       ],
       [ 2.61710037,  2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.90569716,  2.1784656 ,  2.1784656 ,  2.1784656 ,  2.1784656 ],
       [ 2.61710037,  2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.61710037,  2.        ,  2.        ,  2.        ,  2.        ]])

In [8]:
M

array([[  5.,   2.,   4.,   4.,   3.],
       [  3.,   1.,   2.,   4.,   1.],
       [  2.,  nan,   3.,   1.,   4.],
       [  2.,   5.,   4.,   3.,   5.],
       [  4.,   4.,   5.,   4.,  nan]])

In [27]:
#np.linalg.pinv(np.dot(V,V.T))
def array_sq(l):
    return np.dot(l,l.T)
np.apply_along_axis(array_sq,1,V)

def build_U(M,U,V,reg,d):
    M_rows,M_columns = M.shape
    
    for i in xrange(M_rows):
        temp_1 = np.dot(V.T,V)+reg*np.eye(d)
        temp_1 = np.linalg.pinv(temp_1)
        temp_2 = np.dot(M[i,],V)
        U[i,] = np.dot(temp_2,temp_1)
        print U[i,]

In [51]:
Unp.dot(U[1,:],V[:,1])



2.0

In [28]:
V

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [29]:
build_U(M,U,V,0,2)

[ 1.8  1.8]
[ 1.1  1.1]
[ nan  nan]
[ 1.9  1.9]
[ nan  nan]
